version: "3.8"

services:

  wordpress:
    build:
      context: .
    image: leadstec/wordpress:5.6
    ports:
      - "80:80"
    volumes:
      - ~/volumes/wordpress.local/log:/data/log
      - ~/volumes/wordpress.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - EMAIL=
      - PHP_DEV_CONFIG=true
      - WP_ADMIN_EMAIL=
    secrets:
      - lcs
      - deploy
    hostname: wordpress.local
    container_name: wordpress.local

  db:
    image: leadstec/mariadb:latest
    expose:
      - "3306"
    volumes:
      - ~/volumes/wordpress-db.example.com/log:/data/log
      - ~/volumes/wordpress-db.example.com/db:/data/db
      - ~/volumes/wordpress-db.example.com/persist:/data/persist
    environment:
      - EMAIL=
      - ENGINE=example.com
      - MARIADB_DB_USER=wpuser
      - MARIADB_DB_NAME=wordpress
    secrets:
      - lcs
      - deploy
    hostname: wordpress-db.local
    container_name: wordpress-db.local


secrets:
  lcs:
    file: ~/.vcubi/lcs
  deploy:
    file: ./deploy
